# Generated by Django 6.0.2 on 2026-03-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "₽ Рубли"),
                    ("USD", "$ Доллары"),
                    ("EUR", "€ Евро"),
                    ("KZT", "₸ Тенге"),
                ],
                default="RUB",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
